all: part_a part_b

part_a:
	g++ -std=c++14 -Wall -Werror -O2 -o week11 week11.cpp
part_b:
	g++ -std=c++14 -Wall -Werror -O2 -o week11_2 week11_2.cpp
part_c:
	g++ -std=c++14 -Wall -Werror -O2 -o week11_3 week11_3.cpp
