all: oo threads vector

oo:
	g++ -std=c++14 -Wall -Werror -O2 -o oo_my oo_my.cpp
threads:
	g++ -std=c++14 -Wall -Werror -O2 -o threads_my threads_my.cpp
vector:
	g++ -std=c++14 -Wall -Werror -O2 -o vector_my vector_my.cpp

clean:
	rm oo_my threads_my vector_my
